apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-f7r4
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/test-rhtap-8-tenant/load-app-ab2184f3-92a3-4be8-9f95-0b21d82243d7/devfile-sample-python-basic-f7r4@sha256:43877e8d4efd6abd40ad1b483fc5cc79d01a2a89292caa76133225eb423e61c9
        name: my-python
        resources: {}
status: {}
